### ISSUE TITLE
Not verified by Google

### ISSUE THREAD

**Issue by lbusoni** [jordan2175/markdown-tools#2]
The plugin cannot be installed. The attached screenshot reports that the app has not been verified by Google and cannot be installed

![Schermata 2019-10-16 alle 18 05 58](https://user-images.githubusercontent.com/8113755/66937394-a72f1f80-f03f-11e9-93d7-ff7b7bfcea2f.png)

**Comment by jordan2175** [comment]
I am trying to figure out what Google needs me to do to get it verified.  Stay tuned.

**Comment by jordan2175** [comment]
After much back and forth, Google has now said the app is published and verified.  If you are still having problems, let me know.

**Comment by jordan2175** [comment]
I have verified that this add-on has now been verified by Google. You will no longer get the error message on install.
